### ISSUE TITLE
[Feature]: Developer can cancel a task via the Kubernetes API 

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1040]
### Background

**As a** developer
**I want** to run tasks via the Kubernetes API
**So that** I can execute one-off workloads without needing the `cf` CLI

### Acceptance Criteria

**GIVEN** `task1` is a task with a condition of type `"Created"` and status `"True"`
**AND** `dev1` is a `SpaceDeveloper` in `space1`
**AND** `dev2` is *not* a `SpaceDeveloper` in `space1`
**AND** `mgr` is a `SpaceManager` in `space1`
- **WHEN I** set `spec.canceled` field to `true` for `task1` as `dev1`
  **THEN I** see the task has a new condition of type `"Canceled"` and status `"True"`
  **AND** the task execution is interrupted
- **WHEN I** try to do it as `dev2` or `mgr`
  **THEN I** get a permission error

**GIVEN** a cancelled task
**WHEN** the task execution has been interrupted
**THEN I** see the task has a new condition of type `"Failed"` and status `"True"`

**GIVEN** a task with a condition of type `"Succeeded"` or `"Failed"` and status `"True"`
**WHEN I** set its `spec.canceled` field to `true`
**THEN I** get an error

**Comment by kieron-dev** [comment]
**Warning** There is a possible problem with this implementation.

Sketch of implementation:
* New bool field `canceled` on task spec
* When this is set to `true`, the korifi task reconciler deletes the eirini task and sets the cancelled and failed status conditions
* Deleting the eirini task causes the k8s job to be garbage collected

Potential problems:
* We are anticipating the k8s garbage collector. We set the failed status on the korifi task regardless of what's happening to the k8s job
* Killing the job is an abrupt way of stopping a task. We already know that we can lose the latest output from the job if we kill it too soon after the process terminating (hence the eirini task TTL work), so that could happen here.
* There is a new way (since k8s 1.22) of stopping a task using the suspend field on its spec. This would work well if we didn't have to support earlier k8s versions. This would SIGTERM the job process allowing it to terminate gracefully.

So there might be a case for implementing the cancel logic in the eirini-controller, rather than what we've done in the korifi task controller. There is some reluctance to do this re-work now given we have an almost acceptable solution and we have further re-work required to unify the korifi and eirini-controller task resources.
