### ISSUE TITLE
[Feature]: Set CPU weights based on App memory on RunWorkloads

### ISSUE THREAD

**Issue by akrishna90** [cloudfoundry/korifi#1187]
### Blockers/Dependencies

#1145 

### Background

**As a** app developer
**I want** apps to have some amount of guaranteed CPU
**So that** they do not get completely starved for CPU resources

---
For CPU, the CPU requests on the pod should at least be nonzero to guarantee some degree of CPU availability for the app process. In CF, CPU has not been allocatable directly, and instead has been allocated proportionally to the memory allocation.

### CF on VMs
In CF on VMs, this model has been more flexible than Kubernetes, because the Diego cells do not treat CPU as an explicitly allocatable resource and so do not place an independent bound on the total quantity of CPU shares. Nevertheless, in most cases 8 GB of memory has corresponded to a CPU weight of 100 on a Diego LRP, and then into 1024 CPU shares on a Linux host. We commonly see that 4 CPU x 32 GB is a common size for Diego cell VMs, as a moderately sized high-memory VM configuration on many clouds (GCP n2-highmem, Azure E-series, AWS r-series), so maxing out the memory allocation on the Diego cell means that those 1024 CPU shares correspond to a minimum of 1 CPU of availability.

### Kubernetes
In Kubernetes, the kubelet makes the host CPU available as an explicitly allocatable quantity (in units as granular as millicores), minus any overhead for its own CPU usage. Internally, it translates the CPU requests into CPU shares at 1024 per CPU core.  Since Pods can burst their CPU usage above their requests up to the CPU limit (assuming no other CPU contention), it's also ok to reduce the CPU-to-memory allocation ratio slightly to avoid making CPU the constraining resource to allocate. 

A default of **100m** of CPU request per **1 GiB(1024 MiB)** of memory limit/request would be close to the behavior of CF in practice without going over. We should also make sure that each app has some minimum CPU request (say, **5m**) even if its memory allocation is very small (say, **32 MiB**).

~~- CPU Limits
For CPU limits, which are not exclusively allocated, we should consider setting some high limits as a guard against extreme noisy neighbors without otherwise constraining the flexibility of CPU consumption. One scheme that might work is to set the limit as double the CPU request value, with a minimum limit of 1 CPU to avoid constraining low-memory apps too much.~~

### Acceptance Criteria

**GIVEN** I `cf push test-app -m 1024M`
**WHEN I** inspect the `pod` for `test-app` 
**THEN I** I see `100m` CPU Request set on the pods
~~**THEN I** I see `1` CPU Limit set on the pods~~

**GIVEN** I `cf push test-app -m 25M`
**WHEN I** inspect the `pod` for `test-app` 
**THEN I** I see a `5m` CPU request set on the pods
~~**THEN I** I see `1` CPU Limit set on the pods~~

**GIVEN** I `cf push test-app -m 10G`
**WHEN I** inspect the `pod` for `test-app` 
**THEN I** I see a `1` CPU request set on the pods
~~**THEN I** I see `2` CPU Limit set on the pods~~

### Dev Notes

- Korifi CFProcess to Eirini LRP conversion for CPU weight- https://github.com/cloudfoundry/korifi/blob/a372c18bfd24ee1ca6ee3bdf35c878d907cdcd58/controllers/controllers/workloads/cfprocess_controller.go#L247-L256  
- CF for VMs scales CPU based on the amount of memory that has been allocated to a Process: https://github.com/cloudfoundry/cloud_controller_ng/blob/111c846ceba16771bff030e583449977a593a344/lib/cloud_controller/diego/task_cpu_weight_calculator.rb
- Allowing App Developers to explicitly set CPURequests AND/OR Exposing the ratio for the platform team to configure will be covered in a different story

**Comment by clintyoshimura** [comment]
As per team discussion, it seems it would be better to use a default CPU limit that's hard-coded and high like 2 cores and if the calculated request is higher than that, to set the limit equal to the request. It does occur to me that if we set the limit equal to the request than the pod might become guaranteed (https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/) and that's not something we'd want? So maybe an offset to the limit in the case where the calculated CPU request is higher than 2 cores would be better? 5 millicores maybe?

**Comment by kieron-dev** [comment]
In garden (cf-on-vms), there was an experimental property to set CPU limits, using the same cgroup property that sets k8s CPU limits. This was to limit the noisy neighbour problem, particularly in shared environments (e.g. PWS). This was abandoned as it was not possible to find a value which both suppressed CPU greedy apps and at the same time allowed normal apps to spike their CPU as required during normal operation. The common failure was with apps timing out before becoming ready as their CPU intensive startup phase was throttled.

With this experience, I would suggest being very careful before imposing any CPU limit when we don't have very clear data on CPU behaviour of the entire set of apps on the cluster. An option might be to allow this to be configurable by an operator. But to test the behaviour we should provision a cluster _full_ of typical business apps (e.g. java or spring apps with heavy initialisation requirements) including the odd constantly CPU-hungry app, and see if limits can be used to stop the CPU-hungry apps impacting the other apps, and whether such a limit still allows normal apps with heavy initialisation requirements to start within the cf timeout.

Note that the eventual garden solution to this problem was to monitor historical app CPU usage against a quota, and move apps over their quota into a separate cgroup together where they were more heavily constrained to their CPU 'requests' and leaving other apps to freely burst over their requests while being historically below quota.

**Comment by clintyoshimura** [comment]
After discussion, we decided to calculate the default CPU request as described, but to forgo a default CPU limit. The functionality to allow a user to override the CPU limit can be added as part of the aforementioned separate story to allow a user to set the CPU request if desired.

**Comment by akrishna90** [comment]
Acceptance Passed. Closing the issue
