### ISSUE TITLE
[Chore]: Install korifi controllers in the repository tests

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#1218]
### Background

The repositories in the api shim are predominantly being tested with integration tests, because they are a major part of our boundary with k8s. These integration tests are not running against real clusters, but are using [envtest](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/envtest) instead, because it is lighter and easier to manage. This works pretty well for most test, but there are some that depend on the side effects of some of our controllers (envtest is the api of k8s without the runtime, so crds are generally not reconciled unless the respective controllers are installed). These tests are working around this limitation by simulating what the controller would do in a go routine effectively mocking the controller. This is not ideal because it introduces fake login and encodes certain assumptions in the tests that might not be true or may become outdated

### Action to take

Let's try to remove these simulations and install the respective controllers instead

### Impact

We have a more realistic test suite without giving up the simplicity and lightness of envtest

### Dev Notes

Here are the tests that are simulating controller logic:
- https://github.com/cloudfoundry/korifi/blob/7ccefca205db1499e1353ac06540e36963047ca2/api/repositories/task_repository_test.go#L42-L45
- https://github.com/cloudfoundry/korifi/blob/7ccefca205db1499e1353ac06540e36963047ca2/api/repositories/space_repository_test.go#L73-L92
- https://github.com/cloudfoundry/korifi/blob/7ccefca205db1499e1353ac06540e36963047ca2/api/repositories/org_repository_test.go#L73-L92

**Comment by danail-branekov** [comment]
Today we tried to refactor the org repository test to use env-test with real controllers running on it. We saw several issues:

1. The `DeleteOrg` method just deleted the `CFOrg` resource which turned to be an asynchronous operation as the real org controller installs a finalizer on the `CFOrg` which causes the `delete org` test to fail as it still can find the `CFOrg` resource after `repo.Delete` has returned. We managed to address this issue by putting the check on whether the org is deleted in Eventually (which makes sense for this specific test)

2. The next issue we faced was that the org controller never creates the namespace and the `CFOrg` never gets into `Ready` state. It turned out that the reason is that the org controller requires a `packageRegistrySecret` to be available in the root namespace, which is created by the `install-dependencies.sh` script. This means that if we want to run real controllers in env tests, we should probably replicate `install-dependencies` into the suites setup. This raises the question whether the effort is worth it,  or we should just use kind with korifi-controllers deployed instead.

Alternative, we could keep tests as they are, with the huge drawback that we have to simulate part of the controllers behaviour, i.e. we are testing against an incomplete system. That could potentially hide unforeseen issues.

**Comment by georgethebeatle** [comment]
This chore was created in order to explore a more lightweight alternative of running the integration tests against an actual real kind cluster. The idea was that switching to kind looks like a big effort and might also make tests run more slowly, so we should avoid it if possible. It turned out, however, that envtest is not a good fit for testing repositories against real controllers, because they come with dependencies and installing those dependencies is almost as complex as switching to kind. After discussing the topic with US colleagues we agreed that testing repositories against envtest with real controllers installed is a no go, but we can continue our experiments to find a better fit for those integration tests. There is already a chore (#1034) about looking into using kind and we might log more, so this one can be closed.
