### ISSUE TITLE
[Bug] Duplicate process types created per app

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#1261]
This issue has been exposed by CI build https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-tests-periodic/builds/79

```
Timed out after 10.003s.
  Count of CFProcess is not equal to 1
  Expected
      <[]v1alpha1.CFProcess | len:2, cap:4>: [
          {
............
```

We managed to reproduce the issue locally via focusing the complete `controllers/controllers/workloads/integration/cfapp_controller_integration_test.go` and running ginkgo with `until-it-fails`. It takes <10 times before failing.

Looking at the cfapp reconciler, we see that it first tries to list processes by app guid and process type, and if the results is empty, then creates the `CFProcess` object ([here](https://github.com/cloudfoundry/korifi/blob/3117b0163de8ee3f62fc737bbf6f2430e2b21f5d/controllers/controllers/workloads/cfapp_controller.go#L103-L115)). We believe that this check is not reliable as the list operation might return an outdated empty list thus tricking the reconciler into creating another duplicate process.

**Comment by tcdowney** [comment]
Since we've already moved away from real GUIDs for many of our resources, I think it may be time for the "optimistic locking" approach where we have deterministic names for these processes so that we can do a "create or update" type strategy instead.

The one thing I can think of though is we don't want to wipe out any changes that were made to existing processes... so maybe the "or update" part isn't something we don't want to do. We could just always attempt the create and catch the errors for that maybe.
