### ISSUE TITLE
[Bug]: Fix issue with running ruby apps

### ISSUE THREAD

**Issue by akrishna90** [cloudfoundry/korifi#1439]
### Background

We pinned the version of ruby buildpacks to `v0.11` in this PR #1438 

With Ruby apps, the builds succeeds but the pods fail to start with the latest version. In our controllers, after the build succeeds, we [extract the `start-command` from the built image](https://github.com/cloudfoundry/korifi/blob/c5de457248ebeb7aaad21768a905bce0911b2ec0/kpack-image-builder/controllers/imageprocessfetcher/image_process_fetcher.go#L51-L57) and set it on the cf-process. This seems to work fine with ruby:0.11 but is broken on the latest version.

Inspecting it further, we verified that the `start-command` on the image is the same as the start command we set on the cfprocess

```
   Paketo Rackup Buildpack 0.4.0
     Writing start command
     Assigning launch processes:
       web (default): bash -c bundle exec rackup --env RACK_ENV=production -p "${PORT:-9292}"
```

Removing the command from the cfprocess fixes the issue. As a workaround, we decided to pin the version to 0.11 until we figure out how we want to fix this.

We identified the difference with the `start command` b/w v0.11 & latest
With v0.11
```
bundle exec rackup --env RACK_ENV=production -p "${PORT:-9292}"
```

With latest version
```
 bash -c bundle exec rackup --env RACK_ENV=production -p "${PORT:-9292}"
```

It appears that quoting the command after `bash -c` fixes the issue
```
 bash -c "bundle exec rackup --env RACK_ENV=production -p \"${PORT:-9292}\""
```

### Action to take

@davewalter had the suggestion about not setting the command on the cfprocess resource. It appears that the `command` attribute is not a required field on the `RunWorkload` anyway. 

We have opened a discussion with the `packeto-buildpack` team
 See details - https://paketobuildpacks.slack.com/archives/CULAS8ACD/p1658873060962669

### Impact

This will allow us to use the latest buildpacks for ruby

**Comment by Birdrock** [comment]
>If the -c option is present, then commands are read from string. If there are arguments after the string, they are assigned to the positional parameters, starting with $0.

**Comment by Birdrock** [comment]
It appears this is a result of a change in the rackup buildpack: https://github.com/paketo-buildpacks/rackup/blame/8cc50547eeeda8781e0ec944997514394f2f95f0/build.go#L53-L63

**Comment by Birdrock** [comment]
Where the change to rackup fully comes into play is in the [image_process_fetcher.go](https://github.com/cloudfoundry/korifi/blob/main/kpack-image-builder/controllers/imageprocessfetcher/image_process_fetcher.go#L68-L70) where we join the command and args into a single string. This causes it to be interpreted as `bash -c bundle` with the rest being assigned as args.

**Comment by matt-royal** [comment]
The quickest fix here would be to quote each argument like this:

```golang
func extractFullCommand(process launch.Process) string {
	commandWithArgs := []string{process.Command}
	for _, arg := range process.Args {
	    commandWithArgs = append(commandWithArgs, fmt.Sprintf("%q", arg))
	}
	return strings.Join(commandWithArgs, " ")
}
```

I'm not sure if `fmt.Sprintf("%q")` will correctly shell quote things, so you may need to look into that further.

**Comment by gcapizzi** [comment]
I’ll try to summarise my understanding of this issue, mostly so that we are all on the same page.

#### What's the flow of the command from a built image to a `CFProcess?`

1. When building an image, we [generate the droplet status](https://github.com/cloudfoundry/korifi/blob/260ba1674bccee871c8a02ee0519020d3a2abe1b/kpack-image-builder/controllers/buildworkload_controller.go#L179) by, among the other things, [extracting the process types using the `ImageProcessFetcher`](https://github.com/cloudfoundry/korifi/blob/260ba1674bccee871c8a02ee0519020d3a2abe1b/kpack-image-builder/controllers/buildworkload_controller.go#L306)
    - [`ProcessType`](https://github.com/cloudfoundry/korifi/blob/260ba1674bccee871c8a02ee0519020d3a2abe1b/controllers/api/v1alpha1/cfbuild_types.go#L63-L66) actually also includes a `Command` (which is a `string`)
    - the `ImageProcessFetcher` [generates the aforementioned `Command`](https://github.com/cloudfoundry/korifi/blob/c5de457248ebeb7aaad21768a905bce0911b2ec0/kpack-image-builder/controllers/imageprocessfetcher/image_process_fetcher.go#L55) by [concatenating the command and arguments](https://github.com/cloudfoundry/korifi/blob/c5de457248ebeb7aaad21768a905bce0911b2ec0/kpack-image-builder/controllers/imageprocessfetcher/image_process_fetcher.go#L68-L71) coming from the image process
2. The droplet status gets [copied from the `BuildWorkload` to the `CFBuild`](https://github.com/cloudfoundry/korifi/blob/260ba1674bccee871c8a02ee0519020d3a2abe1b/controllers/controllers/workloads/cfbuild_controller.go#L131)
3. When [starting the app](https://github.com/cloudfoundry/korifi/blob/260ba1674bccee871c8a02ee0519020d3a2abe1b/controllers/controllers/workloads/cfapp_controller.go#L121), we [create the necessary `CFProcess`es](https://github.com/cloudfoundry/korifi/blob/260ba1674bccee871c8a02ee0519020d3a2abe1b/controllers/controllers/workloads/cfapp_controller.go#L155) using the `ProcessType`s from `CFBuild.Status.Droplet`

#### What's the issue with the flow above?

The concatenation performed in `ImageProcessFetcher` drops vital information about the boundaries of each single argument: for example, a command like `"/bin/bash"` with arguments `["-c", "bundle exec ..."]` becomes `"/bin/bash -c bundle exec ..."`, which will result in only `bundle` being passed to `bash -c`!

#### Why do we need to this in the first place? Don't images already have an entrypoint set?

Apps can have [multiple processes](https://buildpacks.io/docs/app-developer-guide/run-an-app/#build-a-multi-process-app), each of which will have its own entrypoint. Using the default image entrypoint would only work for running the `web` process.

#### Possible solution

We could try to quote each individual entry in the arguments list before concatenating. In the example above, this will result in:

```
/bin/bash -c "bundle exec ..."
```

This looks correct. But what happens if the arguments in turn contain quotes? For example, arguments like `["-c", "echo \"hello\""]` would result in:

```
/bin/bash -c "echo "hello""
```

This works in my shell but I'm not sure it will as a general solution.

**Comment by tcdowney** [comment]
> Why do we need to this in the first place? Don't images already have an entrypoint set?
Apps can have [multiple processes](https://buildpacks.io/docs/app-developer-guide/run-an-app/#build-a-multi-process-app), each of which will have its own entrypoint. Using the default image entrypoint would only work for running the web process.

I think this is the most important reason. One other reason (which we could solve in other ways) is that the `GET /v3/processes/:guid` endpoint wants to display the command in all cases. Right now saving it off on the `CFProcess` is a convenient way of making that accessible. Leaving it empty except in cases where it was developer specified could be valid, but we'd still need a way to reach through and find the buildpack-provided command.

* https://github.com/cloudfoundry/cloud_controller_ng/blob/e883d66c780287e2270e561f1b80d73a8ef89714/app/models/runtime/process_model.rb#L407-L413
* https://github.com/cloudfoundry/cloud_controller_ng/blob/e883d66c780287e2270e561f1b80d73a8ef89714/app/presenters/v3/process_presenter.rb#L26

> Using the launchers in /cnb/process
I think there may be some cases where a launcher is not guaranteed to exist for a process type. Such as if a CF manifest declares one, we'll make one, but the buildpack would have no context of it. That might be enough of an edgecase we don't care though. Bigger question I have is: will a buildpack _always_ provide a launcher for a given process type it knows about? It was unclear to me from the spec.
