### ISSUE TITLE
[Chore]: Move pod_webhook and build_pod_webhook into korifi-controllers

### ISSUE THREAD

**Issue by matt-royal** [cloudfoundry/korifi#1530]
### Background

To ease implementation of alternative build and run reconcilers, we want to move as much logic as possible out of them and into the root korifi-controllers. Both the statefulset-runner/api/v1/pod_webhook.go and kpack-image-builder/api/v1alpha1/build_pod_webhook.go contain behavior that will be potentially be useful/required in any build or run reconciler. Furthermore, these webhooks only run on resources with a label in the `korifi.cloudfoundry.org/` prefix, so they are safe to have installed cluster-wide.

### Action to take

Take the webhooks in the following locations and move them into the `korifi/controllers` sub-project:
- `statefulset-runner/api/v1/pod_webhook.go`
- `kpack-image-builder/api/v1alpha1/build_pod_webhook.go`

After the move, ensure that these two webhooks behave as they did before, and that you are still able to push an app and see the health of all of its instances.

### Impact

This chore will simplify the work of implementing alternative build and run reconcilers.

**Comment by gcapizzi** [comment]
I think these responsibilities belong to the builders and runners, as only the specific implementation will now how these pods have been created, if any (e.g. pods might be created on different clusters). For example, `STSPodDefaulter` relies on the fact that pods have been created by a `StatefulSet` so that it can extract the instance index from the name.

**Comment by matt-royal** [comment]
Fair enough. I'll close this issue.
