### ISSUE TITLE
[Explore]: Is Korifi support stratos UI

### ISSUE THREAD

**Issue by mohamedhani** [cloudfoundry/korifi#1531]
### Background

Hi , 

Is korifi support stratos UI or any UI application

### Acceptance Criteria

check if korifi support stratos UI or any UI applicatio

### Timebox

No timebox

**Comment by gcapizzi** [comment]
Hi @mohamedhani! 

I'm not very familiar with Stratos, but I suspect it wouldn't work. Korifi does not use [UAA](https://docs.cloudfoundry.org/concepts/architecture/uaa.html) for authentication, but instead [delegates authentication to Kubernetes](https://github.com/cloudfoundry/korifi/blob/main/docs/user-authentication-overview.md).

Each Kubernetes provider authenticates in a different way, which is why we have modified the `cf` CLI to leverage the same authentication mechanism used by `kubectl`. I don't think there's a straightforward of doing the same thing for Stratos.

We might explore this in the future but it's not a priority at the moment. Thanks for reaching out!
