### ISSUE TITLE
[Chore]: Use `vendir` for our test dependencies

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1554]
### Background

We have recently [stopped shipping YAML files](https://github.com/cloudfoundry/korifi/commit/9a01bbc7aa9d38f8f57709b4076501e3becb66fb) for our dependencies, opting instead of just instructing users on how to install them themselves.

For this reason, we have moved the YAML files for our dependencies to the [tests directory](https://github.com/cloudfoundry/korifi/tree/main/tests/dependencies). This is better but it would be even more convenient to use a tool like [`vendir`](https://carvel.dev/vendir/) to download those dependencies on demand. This would also allow us to keep up with new releases of our dependencies and detect breaking changes.

`vendir` will create a lock file that persists the specific revisions downloaded for each dependency. We should version control it, and always use it (via `vendir sync -l`). Every once in a while, either automatically or manually, we should update this file (via `vendir sync`) and commit it. The contents of this file will allow us to easily document which versions of our dependencies we test against. We could keep the vendored dependencies checked in as well for convenience.

### Action to take

* Introduce the necessary `vendir` configuration.
* Invoke `vendir` where needed to run the tests, locally or on CI.

### Impact

This will free us from the burden of maintaining our own copies of the dependency YAMLs and will allow us to stay up-to-date much more easily.

**Comment by tcdowney** [comment]
@gcapizzi do you imagine we would still check in the vendored `tests/dependencies` files or would we `.gitignore` and pull every time?

**Comment by gcapizzi** [comment]
Oh, I hadn't thought of that option. My idea was to get rid of them entirely, and use the lockfile, but that does result in a bunch of downloads every single time we run the tests. Keeping them would save us from:
- needing to run `vendir sync -l` every time
- checking in the lockfile at all
- downloading stuff every time

so maybe it's a win?

**Comment by tcdowney** [comment]
I'm not sure I have a strong opinion. Not assuming they're checked in avoids the temptation of referring to the files directly in more contexts, but I think having them located under `tests` might be good enough there. Not downloading stuff every time could be good, but I don't know what will remind us to update it at that point. Maybe CI would do it.

> checking in the lockfile at all
I think it's important to check this in regardless -- especially when you have relaxed constraints -- cause otherwise you don't know what is vendored in.

**Comment by gcapizzi** [comment]
Yeah you're right, we don't want to thrown the lockfile away. Not checking them in but still using the lockfile with `sync -l` (which is what I'm advocating for here) will have the same problem re: updates - we'll need to do an update from time to time. I still like the idea as it means we can test the updates before we merge in the updated lockfile, so we should never have broken dependencies on `main`.

**Comment by georgethebeatle** [comment]
We ended up checking the vendored files in and not relying on the vendir lock file. The main reason for doing that was that even with the vendir.lock.yml file checked in `vendir sync -l` would discover and download the dependencies every time, replacing the old ones. It looks like vendir does not check the vendor dir sha sum to prevent excessive downloads. As a result when you run `vendir sync -p` prior to running the tests it is taking a non-negligible amount of time, slowing the test run down. 

It also looks like other projects that use vendir do check in the vendor dir, so we went with that since it also addressed the speed issue.
