### ISSUE TITLE
[Bug]: Org and Space display names don't need to be more strict than CAPI

### ISSUE THREAD

**Issue by dsboulder** [cloudfoundry/korifi#1717]
### What happened?

I'm copying orgs and spaces from CF => Korifi. I understand that my resource names have to be k8s compliant, but I surprised that the copy failed because spaces weren't allowed in displayNames. Why even have display names if they don't match CF?

### What you expected to happen

DisplayNames for CF resources should match the naming restrictions of their CAPI pairs for easy interop

### Acceptance Criteria

GIVEN I have some CAPI orgs and spaces
WHEN I attempt to recreate them as K8s Korifi resources
THEN I can match the displayNames

### How to reproduce it (as minimally and precisely as possible)

Create an org directly using a space in the displayName

### Environment

<some proprietary playing around>

**Comment by tcdowney** [comment]
Here's the CF for VMs Org/Space name regexes for reference:
* https://github.com/cloudfoundry/cloud_controller_ng/blob/a70905ee892592f6d05c5b178abbb1fd36f78b14/app/models/runtime/space.rb#L14
* https://github.com/cloudfoundry/cloud_controller_ng/blob/a70905ee892592f6d05c5b178abbb1fd36f78b14/app/models/runtime/organization.rb#L5

**Comment by gcapizzi** [comment]
This is currently still broken, as we still store org/space display names as labels on namespaces, and valid CF display names are not always valid Kubernetes label values.

It looks like the only reason we still use these labels is quickly filtering namespaces that belong to Korifi in [`NamespacePermissions`](https://github.com/cloudfoundry/korifi/blob/6d4edd4238b6aa02dabe55b586c23a83f5a631ce/api/authorization/namespace_permissions.go#L56). This could be achieved with an empty label, as we don't use the label value at all.

Ideally the label key should change but keeping it would maintain backwards compatibility. We could stop setting it but still use it for filtering for the time being.

Having the org/space name on the namespace is still convenient, so we could move it to an annotation, as annotations have no limitations on their value.

**Comment by tcdowney** [comment]
I was checking out the [K8s docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set) to see what the restrictions here are:

> Valid label value:
>
> * must be 63 characters or less (can be empty),
> * unless empty, must begin and end with an alphanumeric character ([a-z0-9A-Z]),
> * could contain dashes (-), underscores (_), dots (.), and alphanumerics between.

So sounds like whitespace (which may be fairly common) wouldn't work. I was hoping it was just excluding less common characters and we could say we support the label value requirements.

> Having the org/space name on the namespace is still convenient, so we could move it to an annotation, as annotations have no limitations on their value.

I think we'd want an annotation at a bare minimum, but we may also want to consider whether or not we care to maintain this compatibility with CF for VMs. During some user demonstrations and feedback we often get feedback that the GUID namespace names are unwieldy and difficult to discover -- but we can usually explain why this is the case and show how they can filter the namespaces using the labels which turns out well. I think we should consider this use case before opening this up widely.

cc @emalm to get his opinion on giving up the label filtering by org/space name.

**Comment by gcapizzi** [comment]
Blocking until the conversation is resolved!

**Comment by emalm** [comment]
@tcdowney and I discussed this, and I'm not so sure that preserving lookup of a Korifi-managed namespace by the space/org display name is that valuable, but I have seen it be useful to indicate the org/space name somewhere in the namespace's metadata so that there's a reasonable trail back to the CF resources. Here's where I think we landed:

* Add a new `cf.org/org-name` annotation to the generated namespace with the display name of the CF org, and relax the display-name validation to match existing CAPI behavior. (Same for CF spaces and their namespaces, _mutatis mutandis_, and it may be worth it to denormalize the org info onto those namespaces too.)
* Add a new `cf.org/org-guid` label with the name of the corresponding `CFOrg` resource so that clients could still look up a specific namespace with information associated to the CF org. (Same for CFSpaces and their namespaces.)
* Restrict the values allowed for `metadata.name` of `CFOrg` and `CFSpace` resources so they are always valid label values, so that the above labeling works (since those resource names are the org/space "guids").
* Deprecate the `cf.org/org-name` and `cf.org/space-name` labels and start setting their values to something that indicates the deprecation, such as `_.-deprecated-._` with label-valid fancy frills on it. Eventually switch the Korifi components to use the guid labels and not the name ones for the internal filtering.

(Tim, please correct anything I misrepresented!)

**Comment by gcapizzi** [comment]
@emalm @tcdowney #2086 implements everything specified in your comment 🙂 although we were wondering: given the namespace names are already set to be the `CFOrg`/`CFSpace` names, is the `cloudfoundry.org/(org|space)-guid` label needed at all? Users could just filter by name. Getting rid of it would also save us the extra validation on `CFOrg`/`CFSpace` names.

**Comment by tcdowney** [comment]
I think the guid label is still useful because it is guaranteed to be consistent over the life of a resource. For example these are useful queries:

* `kubectl get namespaces -l cloudfoundry.org/org-guid="$(cf org MY_ORG --guid)"`

I think we need the validation on `CFOrg`/`CFSpace` names anyway because those become the namespace names.
https://github.com/cloudfoundry/korifi/blob/c49984a70c005aa6b02c8f9dcb69cc06aa5346df/controllers/controllers/workloads/shared.go#L24

And I think namespace resource names have stricter validations since they are used as part of a Service's host https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names

**Comment by emalm** [comment]
> And I think namespace resource names have stricter validations since they are used as part of a Service's host https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names

Oh, yes, https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#namespaces-and-dns states that namespace names have to be valid RFC 1123 DNS labels, so that's already stricter than the label-value validation.
