### ISSUE TITLE
[Chore]: Investigate why the github-pr-resource is occasionally skipping versions

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#1719]
### Background

We are leveraging the [github-pr-resource](https://github.com/telia-oss/github-pr-resource) to trigger the e2e tests on Concourse for every PR that comes in. For security reasons we are only running PRs that have the `e2e-allowed` label set on them. The `allow-e2e` task, which also watches PRs via the pr resource makes sure the test run is auto-approved if the commiter is a team member or one of our bots. Sadly, sometimes this resource skips some PRs, especially when there are many newly open PRs, like when dependabot does a few bumps. In such cases we need to manually allow e2e execution and potentially rebase or force push the change in order to trigger the tests. This is annoying and slows us down.

### Action to take

Look at the github-pr-resource source code and attempt to fix the problem

### Impact

Smooth PR flow

**Comment by danail-branekov** [comment]
See https://github.com/telia-oss/github-pr-resource/issues/26

Apparently this is an old issue that can occur when rebasing PR branches. The root cause seems to be that the `check` step of the resource is checking the `CommitDate`, rather than the `PushDate` of a commit. When a branch is rebased, the `CommitDate` of a commit do not change, therefore the resource thinks that it is an old one.

The resource used to be checking the `PushDate` but it turned out that the field is `nil` for PRs coming from forks. Switching to checking for `CommitDate` seems to be the way they addressed it. 

The obvious solution of this is to check `PushDate`, if `nil`, fallback to `CommitDate`. This has been [already suggested](https://github.com/telia-oss/github-pr-resource/issues/26#issuecomment-492315513) but it did not get much of an attention. There are multiple PRs opened to address the issue, but none of them has been actually merged. 

However, there are forks of the project and one of them seem to be containing a fix we need: https://github.com/opendoor-labs/github-pr-resource/pull/6

So what can we do:
* Create yet another fork where we cherrypick a fix (or even fix it ourselves if we believe we can do that better)
* Switch to someone else's fork and hope that they maintain it
* Try pushing for fixing the issue (I doubt we could get much attention from the maintainers - the issue is almost 5 years old, multiple fixes/PRs have been proposed, none was actually merged)

**Comment by danail-branekov** [comment]
This commit's message also provides some explanation: https://github.com/ctreatma/github-pr-resource/commit/c9ee5894da2d1a0c8a352954d9e60c0a9ca15e94


On standup today we discussed that we need to make sure that the issue above is the culprit.

We should probably wait for the issue to occur and try debugging the check step of the resource to figure out why such PRs remain unnoticed.

**Comment by danail-branekov** [comment]
It just happened again: https://github.com/cloudfoundry/korifi/issues/1719

Could be useful to run the check of the resource to figure out why it is not being picked up

**Comment by kieron-dev** [comment]
We've decided to cherry-pick https://github.com/telia-oss/github-pr-resource/pull/205 into eirini-forks. We agree with the argument that the date filtering is wrong and causes skips. We don't care about extra versions returned that concourse will filter out anyway. So it looks like a simple fix that we can maintain if upstream ever moves again.

So let's see how this goes...

**Comment by kieron-dev** [comment]
Re-opening this as it missed 2 PRs this morning :(

**Comment by kieron-dev** [comment]
It was a pipeline problem. We set pr-label to trigger on all versions, and that will fix it.
