### ISSUE TITLE
[Chore]: Apply the "ask for forgiveness, not permission" principle when creating resources in our controllers

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#1721]
### Background

Most of our controllers need to create certain objects if they do not exist as part of the reconciliation loop. Here is one example: https://github.com/cloudfoundry/korifi/blob/81f389cfc0ef69c5d05c784162ba3b9bee742341/controllers/controllers/workloads/cfapp_controller.go#L404-L434

This code is potentially racy, because the object might be created right after the check (this might not be a concern since Reconcile might be unlikely to run concurrently, which I am not sure about). Furthermore it costs us two calls to the apiserver.

### Action to take

Make sure that in  cases like the one pointed out above we attempt creation straight away and ignore the `AlreadyExistsError`. 

### Impact

This eliminates a potential race and takes out one call to the apiserver

**Comment by adamfowleruk** [comment]
From a usability standpoint this would be great as this kind of thing is really annoying about Kubernetes. If we can avoid forcing developers to know the entire known state of the app when we know their next command would just delete the object anyway, then it'll be a much more joyful experience.

**Comment by danail-branekov** [comment]
The trivial chore turned out to be complicated :)

Here is the train of thought that lead to that
1. Sometimes the controller does not only create an object, it uses it later on (e.g. to set an ownership, to check its status, whatever). In such cases `create` + ignoring the `AlreadyExists` error is not enough, on `AlreadyExists` the controller should get the object. Now this is the reverse to `get` + `create is not found`.
1. So if the object is needed, then why not just use `controllerutils.CreateOrPatch`? That is the next problem: if `Patch` fails as it e.g. trie to update an immutable field then how do you handle that? How do you propagate the error to the user? Just logging the error is obviously not good enough.
1. If we want to guard ourselves from changing immutable fields, we should ensure that korifi resources cannot be changed in a way that this is necessary. Thus a related [explore](https://github.com/cloudfoundry/korifi/issues/2095) has been created
1. However, it is still possible that patching consistently fails for whatever reason. We should be able to communicate this error to the user, so we were thinking of introducing a `Ready` status on every object and wait on that status everywhere from the API (TODO: link to the explore)

**Comment by danail-branekov** [comment]
Blocking on https://github.com/cloudfoundry/korifi/issues/2095 and https://github.com/cloudfoundry/korifi/issues/2098

**Comment by georgethebeatle** [comment]
Racy code in a reconciler is not an issue as reconciliation has the goal of achieving eventual consistency.
