### ISSUE TITLE
[Feature]: Operator can deploy a fully functional Korifi running in only two containers

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1904]
### Background

**As an** operator
**I want** to run Korifi using a minimum amount of containers
**So that** I can minimise the overhead of Korifi

### Acceptance Criteria

**GIVEN** I have installed Korifi
**WHEN I** check the pods running in the Korifi system namespace
**THEN I** see there's only two, one for the `api` and one for `controllers`

**GIVEN** I have installed Korifi
**AND** I have set a `<component>.include` flag to `false`
**WHEN I** I try to exercise `<component>`
**THEN I** see it's not running

### Dev Notes

* This should allow us to get rid of a bunch of `global` Helm values that now don't need to be global anymore.
* We want to reuse the `<component>.include` flags to decide wether to add a component to the main controllers manager or not.
* Does this justify getting rid Helm subcharts altogether?
* From a code architecture standpoint, we could maintain the current go modules as they are, importing them in the `controllers` module, but getting rid of `main.go`s.

**Comment by georgethebeatle** [comment]
We decided to park this track in favour of getting eks support out in next release. All state is pushed to this [wip branch](https://github.com/cloudfoundry/korifi/tree/issues/1904-few-containers).

Here are some useful hints for whoever picks that back up:
- We have merged all subcharts into the korifi helm chart
- There is one values file now and it is important to make sure that we properly merge the values schemas so that we do not drop the required constraint on any field
- We have to change the generated pod webhook manifest to include an object selector for just cf workloads (otherwise no pod that does not come from a statefulset will ever come up once korifi is installed). There is a proposed object selector below
- We can drop the `global` section from the values file now that we no longer have subcharts.

Here is a suggestion of what the webhook object selector could look like:
```
objectSelector:
     matchExpressions:
     - key: "korifi.cloudfoundry.org/guid"
       operator: Exists
```
