### ISSUE TITLE
[Feature]: Operator can use different log levels effectively

### ISSUE THREAD

**Issue by julian-hj** [cloudfoundry/korifi#1926]
### Blockers/Dependencies

#1925

### Background

**As an** Operator 
**I want** log levels to be used accurately
**So that** I can set the verbosity of my logs and get predictable results

### Acceptance Criteria

**GIVEN** a korifi deployment
**WHEN I** set log levels to debug, info, error
**THEN I** see that log verbosity has changed to include the level of logging I desire

### Dev Notes

This story will require us to do an audit of the logging we have in place today and determine whether each log message is leveled correctly.

Error level - should be used sparingly, to indicate that something is broken on the server or in the installation parameters. (http 50x errors)
Info level - should be used to provide low-frequency informational messages (e.g. server is starting up, configuration changes are detected etc.) or user-sourced errors (http 40x errors)
Debug level - everything else.

**Comment by acosta11** [comment]
WIP commit on our feature branch has most of the error level logs audited. We had the following notes while going through those (will edit to tidy these up tomorrow):

Main.go startup errors
- All of these fit the error level description

Controller labelSelector error
- Seems like a very limited code level error

Controller finalizer error
Controller ownerRef error
- In memory change that only fails if the owner does not successfully bind from the schema
    - Coding error or schema initialization error

Controller listCRD error
Controller createOrPatch error
- K8s API interaction on behalf of the system instead of a user could signal actual config error that’s worth surfacing at error level

Finalizer set or removed lifecycle event debug
- Good example of a debug log

TODO - is the semver object initialization in the supported cli version middleware worth elevating to a startup function that errors?

Controller getCRD error
TODO - do we want to generally handle the notFound case at debug level given the noise from delete events that trigger reconcile?

fetchProcessByType appears to be double logging errors
TODO - bubble up the error without logging at the lower level?

Do we want to just remove the top level logging from functions that receive a logger for the purposes of decorating and handling their own logging?
TODO - validate that places where we modified error logs to be fmt.Errorf are not just instances of this new potential convention
TODO - do we want to avoid passing through a logger without further decorating the logs it produces?

Webhook validation errors
- Do we log a separate error in the api/controller layer anyway? Probably. Does that mean these logs should be at info level?

TODO - some error messages suggest that conversion logic is the cause of a failure when we only have an ownerRef failure in the helper function implementation. Might be worth rewording the message or logging directly where the ownerRef error is getting generated.

**Comment by julian-hj** [comment]
LGTM
