### ISSUE TITLE
[Feature]: Developer can see consistent "reason"s on Korifi resources when something bad happens

### ISSUE THREAD

**Issue by julian-hj** [cloudfoundry/korifi#2166]
### Background

**As a** Developer
**I want** consistent and meaningful "reasons" on k8s resources when there is a failure
**So that** I can debug more easily

### Acceptance Criteria

**GIVEN** it's another day in the office
**WHEN I** inspect the Korifi code
**THEN I** see that we are assigning consistent  and meaningful "reason"s to failure events, in PascalCase

### Dev Notes

Specifically:
* cf_app_controller puts an erroneous "appStaged" reason on an unstaged app: https://github.com/cloudfoundry/korifi/blob/main/controllers/controllers/workloads/cfapp_controller.go#L91
 * cf_app controller puts an erroneous "unimplemented" reason on a condition: https://github.com/cloudfoundry/korifi/blob/main/controllers/controllers/workloads/cfapp_controller.go#L98
 * cfbuild_controller uses a "BuildWorkload" reason and message everywhere which has no meaning. Message is optional and could be left blank. Reason should have a better meaning. Also we should be case consistent. https://github.com/cloudfoundry/korifi/blob/main/controllers/controllers/workloads/cfbuild_controller.go#L119
 * Lots of places have "reason" in lowerCamelCase, but we should standardize on PascalCase (CamelCase with initial letter capitalized).
* [Kubernetes API Conventions doc that discusses Status conditions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties)

**Comment by matt-royal** [comment]
In reviewing `cf_app_controller` we made a few observations:
  - `Staged` is a misleading condition, because it actually indicates that a valid droplet is assigned to the `App`. That droplet might have just been staged, or it might be an old droplet that was reassigned to the App. It would be more accurate to say that the App is `Ready` instead. An app would start as `Ready` false and then become `Ready` true when a valid droplet ref is assigned.
  
  - `Running` is also misleading. The actual place to verify that the App processes are running is to look at the CFProcess objects or the pods that they scheduled. What we're really indicating here is that the user has assigned a droplet and the app has a `DesiredState` of `Started`. It would be clearer if we communicated this by setting an `ObservedGeneration` field on the status. An app *should* be running when it is `Ready`, has its `DesiredState` set to `Running`, and has a `Status.ObservedGeneration` equal to `Metadata.Generation`.
