### ISSUE TITLE
[Feature]: Korifi API users can check whether ssh for apps is enabled

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#2326]
### Blockers/Dependencies

No response

### Background

As a CF API client I want to be able to check whether an app supports ssh so that I can see that ssh to apps has been disabled

### Acceptance Criteria

GIVEN Korifi is deployed
WHEN I request

```
curl "https://api.example.org/v3/apps/:guid/ssh_enabled" \
  -X GET \
  -H "Authorization: bearer [token]"
```

THEN I get the following response:

```
HTTP/1.1 200 OK
Content-Type: application/json

{
  "enabled": false,
  "reason": "Disabled globally"
}

```

### Dev Notes

We should not really implement anything related to apps behaviour, we should just ensure that the call succeeds

**Comment by tcdowney** [comment]
## Acceptance

1. Pushed an app
2. Hit the endpoint and it looked as expected

```
$ cf curl /v3/apps/$(cf app node --guid)/ssh_enabled
{"enabled":false,"reason":"Disabled globally"}
```

Note: It actually does this for anything regardless of whether or not the app exists. That's fine since it doesn't leak any additional information about the system that way and knowing that Korifi doesn't support SSH-ing into apps doesn't impact anything.

```
$ cf curl /v3/apps/foobar/ssh_enabled
{"enabled":false,"reason":"Disabled globally"}
```

This looks good to me, going to consider this accepted.
