### ISSUE TITLE
[WONTFIX]: Platform Engineer can limit ephemeral disk used during staging using `stagingRequirements.diskMB` install value

### ISSUE THREAD

**Issue by julian-hj** [cloudfoundry/korifi#2651]
### Blockers/Dependencies

none

### Background

**As a** Platform Engineer
**I want** to be able to set an ephemeral disk limit for staging apps
**So that** I have more predictable utilization of my platform

We noticed that the [diskMB setting](https://github.com/cloudfoundry/korifi/blob/main/helm/korifi/values.schema.json#L182-L185) under `api.stagingRequirements` is used to populate a value in the CFBuild custom resource, but that value is subsequently ignored in the controllers layer, and not propagated to the BuildWorkload.

### Acceptance Criteria

**GIVEN** I have configured the `stagingRequirements.diskMB` Helm value
**WHEN I** `cf push` an app
**THEN I** see that there is an `ephemeral-disk` **limit** on the kpack `Image` / `Pod` performing the build corresponding with the value I set

### Dev Notes

There are 2 possible implementation paths for this story:
1. We are already setting the diskMB value into the CFBuild object. We could create a new field on the BuildWorkload to propagate this value to the build reconciler and get it from there.
2. We could ignore the CFBuild property, and set the value directly on the Image in the controller, as we are currently doing for the buildCacheMB property. If we take this approach, then we should mark the property in CFBuild as unimplemented, since it will continue to be ignored.

(See Tim's comment below. Option 2 looks like the better option)

**Comment by tcdowney** [comment]
Thinking about the two implementation options:

I think these global installation properties make the most sense to be interpreted as limits and that the [ones on the CFBuild](https://github.com/cloudfoundry/korifi/blob/main/controllers/api/v1alpha1/cfbuild_types.go#L31-L34) should be interpreted as requests since developers have the freedom to set those themselves.

I think we should do option two, change the description on those CFBuild properties to mention "request" instead of "limit" and mark them as unimplemented. Then if we ever get to implementing them we'd treat them as request values and we'd have similar behavior to what CF for VMs does (essentially the min of the operator defined limit and dev requested value).

https://github.com/cloudfoundry/cloud_controller_ng/blob/1750fecda6f268ee4c9ecd826db5f5b8d565ab91/app/actions/build_create.rb#L148-L162

**Comment by tcdowney** [comment]
This was effectively undone by https://github.com/cloudfoundry/korifi/pull/2685.

This feature was originally oriented around setting limits. After some discussion on a [Slack thread](https://cloudfoundry.slack.com/archives/C0297673ASK/p1689178733777159) and a [Github issue](https://github.com/cloudfoundry/korifi/issues/2682) we decided to undo that. The original [CF installation properties](https://github.com/cloudfoundry/capi-release/blob/ca8243552af68d30847021d4018f067568d685bf/jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb#L251-L252) were interpreted as a minimum resource request versus a hard limit so we made this value optional (no requests) and allow operators to specify it if they want to set that minimum.

CF for VMs uses a [quota system](https://docs.cloudfoundry.org/adminguide/quota-plans.html) to set operator-specified limits -- so that might be something worth exploring if we want to do this in the future. Given that we don't want to do this right now and that the implementation/UX should likely look very different, I am going to close this issue as "wontfix".
