### ISSUE TITLE
[Explore]: FYI https://github.com/google/kf exists

### ISSUE THREAD

**Issue by hab25** [cloudfoundry/korifi#2762]
### Background

It is licensed under the `Apache License 2.0`.

### Acceptance Criteria

Looking at that code probably can greatly and often help development here. 

### Timebox

No timebox

### Dev Notes

Sorry if this is noise. I couldn't join the slack and felt that it is too important to risk going unmentioned.

**Comment by tcdowney** [comment]
Hi @hab25, thanks for stopping by!

We have looked at `kf` in the past, but the design is quite different from Korifi. Korifi aims to provide a CF compatible API so that the existing CF CLI and other clients can continue to work with it, whereas `kf` provides a replacement CLI that interacts directly with the Kubernetes cluster. For example, [here](https://github.com/google/kf/blob/main/pkg/kf/commands/apps/push.go) you can see how it reimplements the `cf push` command to interact directly with the cluster. As you can imagine, this makes the implementation quite different between `kf` and `korifi`.

We also had a CF on K8s working group sync where someone from the `kf` team stopped by and chatted about it with us. It's recorded here if you're curious and want to watch:
https://www.youtube.com/watch?v=t_LjfBAT7y4

That said, are there specific features of `kf` that you are interested in that you think Korifi should support? We're always looking for user feedback about what to develop next!

Side note, did you run into problems joining Slack? Or did you just prefer not to. If it's the former and you had some problem with the invite flow on https://slack.cloudfoundry.org/ we would like to help you figure that out.

**Comment by tcdowney** [comment]
Cool, glad that worked! We're all in the `#korifi-dev` channel on CF Slack if you want to have a higher fidelity conversation on any of this.
