### ISSUE TITLE
[Chore]: try coq for nvim completion

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#629]
### Background

Our current choice for a vim plugin is https://github.com/hrsh7th/nvim-cmp which is not great according to our experience. [According to an nvim maintainer](https://github.com/nvim-lua/completion-nvim/commit/87b0f86da3dffef63b42845049c648b5d90f1c4d) the other reccommended option is [coq nvim](https://github.com/ms-jpq/coq_nvim)

### Action to take

Try coq nvim as an nvim completion plugin

### Impact

It hopefully works better

### Dev Notes

We should think about how to preserve snippets that we are used to, since coq nvim seems to be handling them differently than [ultisnips](https://github.com/SirVer/ultisnips)

**Comment by kieron-dev** [comment]
We've enabled coq_nvim in https://github.com/eirini-forks/eirini-home/commit/66bd1bffed00da6d69fb50f7fd9e00a4aee3e70b. We've also copied the Ginkgo/Gomega snippets that we had installed locally into the coq format, so that they can be selected in the completion menu.

We have left UltiSnips installed. You can trigger that as usual with \<C-j>. That remains useful for json/yaml tag insertion in structs, or if you fancy fewer keystrokes for a `exen` insertion.

After install, you should run `:COQdeps` and `:COQsnips install`. Unfortunately the warning that says you need to do that requires an enter press, and that stops us being able to script that. A fix [has been done in nvim](https://github.com/neovim/neovim/issues/9358) for that though, so we've included these actions in the eirini-home install.sh script.
