### ISSUE TITLE
[Chore]: Fix e2e flake where all tests creating droplets timeout after 4 minutes

### ISSUE THREAD

**Issue by kieron-dev** [cloudfoundry/korifi#692]
### Background

There is an occasional problem when running e2e tests both locally and in github actions. The tests create an app, a package, upload the node test app, create a build, then wait for kpack to create the app image and update the build status making it a droplet.

When the tests fail, the build never makes it to the droplet stage. Once this happens locally, it will happen consistently until the kind cluster is destroyed. The kpack builds seem to fail with an error to do with the docker registry:
```
Status:
  Conditions:
    Last Transition Time:  2022-02-22T15:49:14Z
    Message:               unable to fetch remote builder image: GET http://localregistry-docker-registry.default.svc.cluster.local:30050/v2/cf-relint-greengrass/cf-k8s-controllers/kpack/beta/manifests/
sha256:17a58aecc2978c6fd4373c3f5e82648286d1575350ea32f57fb34f9517646243: MANIFEST_UNKNOWN: manifest unknown; map[Name:cf-relint-greengrass/cf-k8s-controllers/kpack/beta Revision:sha256:17a58aecc2978c6fd
4373c3f5e82648286d1575350ea32f57fb34f9517646243]
    Status:                False
    Type:                  Succeeded
  Observed Generation:     1
  Stack:
```

Here's an example from github actions: https://github.com/cloudfoundry/cf-k8s-controllers/runs/5273869510?check_suite_focus=true. Though there's not much that can be inferred from that. We really need to see more logs from the cluster.

### Action to take

Identify and fix the flake.

### Impact

PRs will glide through github actions without unnecessary friction.

**Comment by kieron-dev** [comment]
Now I can't trigger this locally. So let's leave this chore around till someone does see this locally, then they can check out the kpack logs, or whatever...

**Comment by danail-branekov** [comment]
I think we (with @georgethebeatle ) got it! :)

When the CFBuild controller creates the kpack image, it puts a reference to the `image-registry-credentials` that is used to push the image to docker. However, due to the delay of objects propagation by the hierarchical namespace controller, that secret is not yet available by the time the kpack controller reconciles the image and creates the build, therefore the build goes in status "secret image-registry-credentials not found". Even though the secret appears in a while (about 2 seconds), the build does not recover.

We are looking at a fix in the CFBuild controller to not create the kpack image if the secrets referenced by the CFPackage are not available
