### ISSUE TITLE
[Chore]: Look for opportunities to speed up API e2e testing

### ISSUE THREAD

**Issue by julian-hj** [cloudfoundry/korifi#705]
### Background

We noticed that the current e2e api tests take quite a lot of time for setup for each test--something like 6 minutes a test.

This will quickly become very painful as we add more tests to the suite.

We should look for ways to speed things up. 

### Action to take

new

### Impact

medium

### Dev Notes

Some starter ideas are:
- Side-load the buildpack image into kind (like we do with the api & controller images). Cache it locally so that we don't have to re-download it on each test run.
- Share the org between tests and only build and tear down the space
- Use a binary app for cf push. Or a golang app. Or whatever is fastest.
- CF push a single "read-only" app in the `beforeSuite` that can be used for testing GET endpoints so that we don't have to do as much test setup.

**Comment by georgethebeatle** [comment]
Maybe another opportunity to further speed them up will be to deploy a long running gke cluster and add a new job that deploys stuff to that cluster when a PR is submitted. A complication here will be that PR workflows in github are unprivileged and therefore have no access to secrets, so it might be interesting how we pass the kubeconfig on.

**Comment by georgethebeatle** [comment]
Another one that we already started workig on is #572 which actually aims at speeding up the product itself.

**Comment by acosta11** [comment]
Today we tried pushing a cross compiled go executable as a binary app instead of the existing node app and saw a change from around 30 seconds to 25 seconds on push time. So we may pursue that if we find we're pushing apps frequently. But we only found 7 tests that use the existing `pushNodeApp` helper in their setup, so the potential time savings may not be as significant as we would like.

Similarly, we're looking at pre-pushing a single app in the  `BeforeSuite` (instead of the `BeforeAll` proposed on #717) to act as a read only resource to test api get endpoints. We're not sure whether user permissions are concern for this idea given the potential for test pollution if we just used a normal space developer role and the app was modified in some way. And similarly to the node vs binary app, there appears to only be 7 uses of the node app helper function.

This leaves trying to re-use orgs in between tests from the list of ideas.

**Comment by julian-hj** [comment]
Thanks @georgethebeatle. Should we close this issue for now? I am not sure that it is still useful to have open.

**Comment by georgethebeatle** [comment]
We are not actively looking into it and it sounds like you aren't either, so closing for the time being.

**Comment by kieron-dev** [comment]
Adding some more thoughts that came up today:

1. We might reconsider our use of terraform in CI. At the moment we follow the recommended terraform configuration which creates a cluster and then deletes and recreates its node pool. This prevents terraform config changes forcing a whole cluster recreation apparently. The creation takes around 10 minutes to complete, so we perform it overnight, and reuse the cluster for each e2e run.

    Note that the equivalent gcloud command `gcloud container clusters create ...` takes around 3 minutes to bring the cluster up. So could we benefit from a simpler approach, given that we only create and delete clusters?

2. And might we consider creating clusters on demand? For instance, we could ensure we always have a clean cluster available for the next test. We could implement a pool system where a test takes a clean cluster from the pool, which would trigger creating a new cluster. And the used cluster would be deleted when returned to the pool. This would allow e2e test parallelisation, which we currently lack.

3. The `gcloud` command to create a cluster creates nodes using the e2-medium machine type (1 vCPU / 4 GiB RAM). We currently use n1-standard-8 (8 vCPU / 30 GiB RAM). The e2-medium type feels reasonably responsive, even though the resources are much smaller. Maybe we could experiment with different machine types to find a CPU / RAM mix that is optimised for the e2e run use case?
